In [ ]:
#multilayer perceptron
import numpy as np

def sig(x):
    return 1/(1+np.exp(-x))

#w=np.array([1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0])

w_node1 = np.array([1.0,1.0,1.0,1.0] , dtype=np.float128)
w_node2 = np.array([1.0,1.0,1.0,1.0] , dtype=np.float128)
w_node3 = np.array([1.0,1.0,1.0,1.0] , dtype=np.float128)

w_node_2nd = np.array([1.0,1.0,1.0], dtype=np.float128)
hidden_output = np.array([0,0,0] , dtype=np.float128)

#dw=np.array([1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0])

bias=np.array([1.0,1.0], dtype=np.float128)
input_x =np.array([2,2,3,3,1,2,3,3,2,1,4,1], dtype=np.float128)
input_x = np.reshape(input_x,(3,4))

print(input_x)

print('element: ' , input_x[0][0])
y_org=np.array([0,0,1], dtype=np.float128)
epsi = .00001
learning_rate=0.25
y_pred=0
err=1
epoch=0


for i in range (3):

  w_node1 = np.array([1.0,1.0,1.0,1.0] , dtype=np.float128)
  w_node2 = np.array([1.0,1.0,1.0,1.0] , dtype=np.float128)
  w_node3 = np.array([1.0,1.0,1.0,1.0] , dtype=np.float128)

  w_node_2nd = np.array([1.0,1.0,1.0], dtype=np.float128)
  hidden_output = np.array([0,0,0] , dtype=np.float128)

  while((err>epsi) and epoch<100):

      hidden_output[0]=sig(np.dot(w_node1 , input_x[i] ) + bias[0])
      hidden_output[1]=sig(np.dot(w_node2 , input_x[i] ) + bias[0])
      hidden_output[2]=sig(np.dot(w_node3 , input_x[i] ) + bias[0])

      y_pred=sig(np.dot(w_node_2nd , hidden_output ) + bias[1])

      err=abs(y_pred-y_org[i])

      w_node_2nd[0] =  w_node_2nd[0] - learning_rate* (err)*y_pred*(1-y_pred) *hidden_output[0]
      w_node_2nd[1] =  w_node_2nd[1] - learning_rate* (err)*y_pred*(1-y_pred) *hidden_output[1]
      w_node_2nd[2] =  w_node_2nd[2] - learning_rate* (err)*y_pred*(1-y_pred) *hidden_output[2]

      w_node1[0] = w_node1[0] - learning_rate* (err)*y_pred*(1-y_pred)*w_node_2nd[0] *input_x[i][0]
      w_node1[1] = w_node1[1] - learning_rate* (err)*y_pred*(1-y_pred)*w_node_2nd[0] *input_x[i][1]
      w_node1[2] = w_node1[2] - learning_rate* (err)*y_pred*(1-y_pred)*w_node_2nd[0] *input_x[i][2]
      w_node1[3] = w_node1[3] - learning_rate* (err)*y_pred*(1-y_pred)*w_node_2nd[0] *input_x[i][3]

      w_node2[0] = w_node2[0] - learning_rate* (err)*y_pred*(1-y_pred)*w_node_2nd[1] *input_x[i][0]
      w_node2[1] = w_node2[1] - learning_rate* (err)*y_pred*(1-y_pred)*w_node_2nd[1] *input_x[i][1]
      w_node2[2] = w_node2[2] - learning_rate* (err)*y_pred*(1-y_pred)*w_node_2nd[1] *input_x[i][2]
      w_node2[3] = w_node2[3] - learning_rate* (err)*y_pred*(1-y_pred)*w_node_2nd[1] *input_x[i][3]

      w_node3[0] = w_node3[0] - learning_rate* (err)*y_pred*(1-y_pred)*w_node_2nd[2] *input_x[i][0]
      w_node3[1] = w_node3[1] - learning_rate* (err)*y_pred*(1-y_pred)*w_node_2nd[2] *input_x[i][1]
      w_node3[2] = w_node3[2] - learning_rate* (err)*y_pred*(1-y_pred)*w_node_2nd[2] *input_x[i][2]
      w_node3[3] = w_node3[3] - learning_rate* (err)*y_pred*(1-y_pred)*w_node_2nd[2] *input_x[i][3]


      epoch = epoch + 1


  print('Prediction after pass', i ,' = ' ,y_pred)

[[2. 2. 3. 3.]
 [1. 2. 3. 3.]
 [2. 1. 4. 1.]]
element:  2.0
Prediction after pass 0  =  0.731061980263935485
Prediction after pass 1  =  0.731061980263935485
Prediction after pass 2  =  0.731061980263935485
