In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import math , sys

In [ ]:
#Creating a 2-D Array
x = np.array ( [ [4,7,2] , [6,8,9] ] )
print(x)

[[4 7 2]
 [6 8 9]]


In [ ]:
#Deriving the shape of some array
#2 Rows , 3 Columns
x.shape

(2, 3)

In [ ]:
#Finding the size
x.size

6

In [ ]:
#Creating an array using numpy , arange() and reshape()
x = np.arange(0,20,1).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
#Number Of columns is generic in this case.
x = np.arange(0,20,1).reshape(2,-1)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [ ]:
#Printing Rows i.e. Slicing specific rows
x = np.arange(0,80,1).reshape(-1,5)
print(x)
slice = x[1]
print('\nExtracting 2nd Row:')
print(slice)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]]

Extracting 2nd Row:
[5 6 7 8 9]


In [ ]:
#start:end:step , start:end:step
y=x[1:6:2]
print(y)

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]


In [ ]:
#Printing columns using slicing
#[ Rows args* , Columns args*]
#start:end:step , start:end:step
y = x[::,0:5:2]
print(y)

y = x[0:5:2,0:5:2]
print('\n',y)

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]
 [25 27 29]
 [30 32 34]
 [35 37 39]
 [40 42 44]
 [45 47 49]
 [50 52 54]
 [55 57 59]
 [60 62 64]
 [65 67 69]
 [70 72 74]
 [75 77 79]]

 [[ 0  2  4]
 [10 12 14]
 [20 22 24]]


In [ ]:
#Slicing rows and columns
y = x[1:3 , 1:4]
print(y)

[[ 6  7  8]
 [11 12 13]]


In [ ]:
#Initializing an array using linspace()
x = np.linspace(0,9,20).reshape(4,-1)
print(x)

[[0.         0.47368421 0.94736842 1.42105263 1.89473684]
 [2.36842105 2.84210526 3.31578947 3.78947368 4.26315789]
 [4.73684211 5.21052632 5.68421053 6.15789474 6.63157895]
 [7.10526316 7.57894737 8.05263158 8.52631579 9.        ]]


In [ ]:
#Matrix Addition in numpy

a = np.arange(0,20).reshape(4,5)
b = np.arange(20,40).reshape(4,5)

print('Matrix a = \n',a,'\n')
print('Matrix b = \n',b,'\n')

c = a + b

print('a + b = \n',c)

Matrix a = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

Matrix b = 
 [[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]] 

a + b = 
 [[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]]


In [ ]:
#Horizontal Stacking, number of rows should be same.
z =np.hstack( [a,b])
print('Horizontal Stacking \n',z)
print(z.shape)

#Vertical Stacking, number of columns should be same.
z =np.vstack( [a,b])
print('\n Vertical Stacking \n',z)
print(z.shape)


Horizontal Stacking 
 [[ 0  1  2  3  4 20 21 22 23 24]
 [ 5  6  7  8  9 25 26 27 28 29]
 [10 11 12 13 14 30 31 32 33 34]
 [15 16 17 18 19 35 36 37 38 39]]
(4, 10)

 Vertical Stacking 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
(8, 5)


In [ ]:
#Finding max element in a matrix/array
#Python
print( x.max() )
#numpy
np.max(x)

9.0


9.0

In [ ]:
#Maximim of an axis
print( x.max(axis=1))
print( x.max(axis=0))

[1.89473684 4.26315789 6.63157895 9.        ]
[7.10526316 7.57894737 8.05263158 8.52631579 9.        ]
